name: Mirror to Bitbucket Repo

on: [ push, delete, create ]

concurrency:
  group: git-mirror

jobs:
  git-mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_SSH_PRIVATE_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.GITEE_SSH_KNOWN_HOSTS }}
        with:
          source-repo: 'git@github.com:kdcloudone/kdesign.git'
          destination-repo: 'git@gitee.com:kdcloudone/kdesign.git'